### PR TITLE
Pull leaflet via npm

### LINKED ISSUE #106: Pull leaflet from npm
From a convo on the ember slack with @miguelcobain 

```
here's the general strategy that is working for ember-paper

- resolving the correct path in npm 2 and >3: https://github.com/miguelcobain/ember-paper/blob/master/index.js#L133-L139
- adding the package in `dependencies`: https://github.com/miguelcobain/ember-paper/blob/master/package.json#L57 (edited)

With that resolved path, I'm assuming you would just `app.import` the file.
```

This would remove the need for a blueprint and would remove the use of bower. Also this would
fix using ember-leaflet in engines (https://github.com/dgeb/ember-engines/issues/226).

Alternative solution to above problem with engines might be https://github.com/runspired/ember-run-raf/pull/14/files

### PR DESCRIPTION
**Pull request by buschtoens**
Closes #106.

### CODE REVIEW

**Comment by buschtoens** [comment]
Sorry for the `package.json` diff. `yarn add` sorts all deps alphabetically. I can go back and add`broccoli-funnel` and `leaflet` by hand, if you like.

**Comment by miguelcobain** [comment]
No problem at all. Thanks for the PR. 

One thing that concerns me is that a lot of people need to use ember-leaflet with leaflet 0.7 (due to some legacy plugin constraints).
Could they use n shrinkwrap with this PR? How so? That process should be outlined in the readme/docs.

**Comment by miguelcobain** [comment]
@buschtoens peerDependencies look nice. 👍 

There is still this blueprint: https://github.com/miguelcobain/ember-leaflet/blob/master/blueprints/ember-leaflet/index.js#L18

That installs the leaflet bower package automatically. I'm sure we can make it install the leaflet npm package and remove 

> You then need to install leaflet via npm / yarn.

**Comment by buschtoens** [comment]
Was just about to mention that. :smile:

**Comment by miguelcobain** [comment]
This is so cool. Thank you!

**Pull request merged**
