### PR TITLE
Feature: Support Ember 5

### LINKED ISSUE #685: Ember 5.x+ Support
Hi, and thanks for this great Ember addon!

I recently installed `ember-leaflet` in an Ember 5.2 based application, and while the addon works perfectly well in Ember 5.x, the addon causes NPM install to fail unless it is run manually using the `--legacy-peer-deps` flag. 

This is because the addon specifies ember as a peer dependency here: https://github.com/miguelcobain/ember-leaflet/blob/master/package.json#L93 

I can open a pull request to update this peer dependency value if required, or the primary maintainers of this repository could simply patch the package.json. I believe package.json simply needs to be altered to support Ember 4.x+ **and** 5.x+ as a peer dependency and then the addon will continue to work with the latest major version of Ember  using `ember install`. 

Thanks!

### PR DESCRIPTION
**Pull request by mdconaway**
Closes #685.

-Upgrades ember-source used in project to 5.2.0
-Updates supported ember peer-deps to ^4.0.0 and ^5.0.0
-Upgrades many libs in package-lock

To test, pull this branch and run `npm install --legacy-peer-deps` (This is required because https://github.com/canufeel/ember-leaflet-marker-cluster has the same peer dependency declaration that causes the npm issue. I created another pull request to fix that library: https://github.com/canufeel/ember-leaflet-marker-cluster/pull/48)

After pulling the branch / installing, run `npm run test:ember` (ember try won't work because of the leaflet-marker-cluster issue)

Additionally, run `npm start` and browse the docs page. All examples listed in docs still work.

### CODE REVIEW

**Comment by miguelcobain** [comment]
@mdconaway https://github.com/canufeel/ember-leaflet-marker-cluster/pull/48 was merged. Maybe we should specify ember-leaflet-marker-cluster `1.1.1` here?

**Comment by mdconaway** [comment]
Agree! Update pushed

**Comment by mdconaway** [comment]
Unsure why the CI runner failed, any recommendations to fix?

**Comment by miguelcobain** [comment]
@mdconaway it appears that the project wasn't quite ready for ember 5 yet. So I kept the ember-source 4 on devDependencies, but still kept the relaxed `"ember-source": "^4.0.0 || ^5.0.0"` peer dependency.

This was released as version `5.1.2`. Please let me know if this worked for you.

**Comment by mdconaway** [comment]
I think this is the dep that may be breaking npm ci:
https://github.com/miguelcobain/ember-composability-tools

Might need a similar patch?

**Comment by mdconaway** [comment]
Not really an error per say. When editing the project locally (and with ember-source set to 5.2.0), everything installs / works fine including `npm run test:ember` and `npm start` after using `npm install --legacy-peer-deps`

However, I did capture the following log messages, which may indicate the dep that breaks `npm ci` which appears to be running in this project's github actions:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: ember-element-helper@0.6.1
npm WARN Found: ember-source@5.2.0
npm WARN node_modules/ember-source
npm WARN   dev ember-source@"~5.2.0" from the root project
npm WARN   9 more (@ember/render-modifiers, @ember/test-helpers, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer ember-source@"^3.8 || 4" from ember-element-helper@0.6.1
npm WARN node_modules/ember-element-helper
npm WARN   ember-element-helper@"^0.6.0" from ember-composability-tools@1.1.0
npm WARN   node_modules/ember-composability-tools
npm WARN 
npm WARN Conflicting peer dependency: ember-source@4.12.3
npm WARN node_modules/ember-source
npm WARN   peer ember-source@"^3.8 || 4" from ember-element-helper@0.6.1
npm WARN   node_modules/ember-element-helper
npm WARN     ember-element-helper@"^0.6.0" from ember-composability-tools@1.1.0
npm WARN     node_modules/ember-composability-tools
npm WARN ERESOLVE overriding peer dependency
```

**Comment by miguelcobain** [comment]
Seems like it comes from ember-element-helper@0.6.0 peer dependencies: https://github.com/tildeio/ember-element-helper/blob/v0.6.0/package.json#L76

And ember-element-helper is a dependency of ember-composability-tools, yes. We can probably fix this by updating ember-element-helper on ember-composability-tools

**Comment by mdconaway** [comment]
Cool, I think ember-element-helper 0.8.3 no longer has the peer-dependency declared. This might enable ember-leaflet to fully upgrade to ember-source 5.2.0! :rocket:

**Comment by miguelcobain** [comment]
@mdconaway released `5.1.3`. Can you retest, please?

**Comment by mdconaway** [comment]
I am only seeing 5.1.2 on NPM. I can try to install from git unless you think 5.1.3 is ready to publish on npm?

**Comment by miguelcobain** [comment]
@mdconaway sorry, I forgot to publish `5.1.3`. Should be good now.

**Comment by mdconaway** [comment]
Ran a project install with 5.1.3 today and didn't see any more peer deps warnings! Thanks for all the help! 🚀

**Pull request merged**
