### PR TITLE
popup fix

### PR DESCRIPTION
**Pull request by gabesmed**

### CODE REVIEW

**Comment by miguelcobain** [comment]
This passes all the tests?

**Comment by gabesmed** [comment]
yeah!

**Comment by miguelcobain** [comment]
Not really sure what this does, but awesome!
Can you elaborate on what is actually happening?

**Comment by gabesmed** [comment]
hehe i'm not sure exactly....but i traced the code behind Ember's new implementation of adding a view to a DOM element, and it looks like this is how it does it.

**Pull request merged**
