### PR TITLE
Rectangle Component

### PR DESCRIPTION
**Pull request by Thatalent**

### CODE REVIEW

**Comment by Thatalent** [comment]
...to address  #12

**Comment by Thatalent** [comment]
@miguelcobain Tried to use `bounds` as the only required params but due to extending polygonLayer, `locations` became a redundant field in `leafletRequiredOptions`. I figure since the api is currently using `locations` for polygonLayers it would make since to just keep it all the same.
I could make some additional changes to replace locations with bounds since that would follow leaflets documentation better but there would be a few places in your docs that would require that change and I didn't want to get ahead of myself.

**Comment by miguelcobain** [comment]
This is very good work @Thatalent, thank you!

Will be released shortly.

**Comment by miguelcobain** [comment]
Released on `4.1.0`

**Pull request merged**
