### PR TITLE
Added rect helper, that generates an instance of L.Rectangle

### LINKED ISSUE #12: L.rectangle component ?
Any plans to add [`L.rectangle`](http://leafletjs.com/reference.html#rectangle)?

### PR DESCRIPTION
**Pull request by badazz91**
... should close  #12.

### CODE REVIEW

**Comment by miguelcobain** [comment]
@badazz91 L.rectangle should be implemented as a component, not a helper.

Where would we use a rect helper?

**Comment by badazz91** [comment]
For instance, one could use it as as an icon for a marker.

**Comment by miguelcobain** [comment]
@badazz91 as you can see, the `setIcon` function needs an instance of `Icon` as a parameter: http://leafletjs.com/reference.html#marker-seticon That was why we created the icon helpers.

Passing in a rectangle instance wouldn't work.

**Comment by badazz91** [comment]
@miguelcobain OUh.... Sorry my bad. Then there was some confusion on my side... I thought there was a need for something similar to the ```point``` helper.

**Comment by miguelcobain** [comment]
@badazz91 the point helper is needed sometimes to create an argument.
But, afaik, there isn't any place where we pass a rectangle as an argument to a layer.

Thanks anyway! Would be great to see the component version of this. :smiley:

**Comment by badazz91** [comment]
@miguelcobain I'll try to give you one ;-)

**Pull request closed without merging**
