### PR TITLE
Test for bug in geojson-layer

### PR DESCRIPTION
**Pull request by allthesignals**
This tests for whether the geojson-layer component re-renders the Leaflet SVG when a style attribute on the component is updated. 

For example, the following will not re-render the SVG after the fill property changes:
```
  this.render(hbs`
    {{#leaflet-map zoom=zoom center=center}}
      {{geojson-layer geoJSON=sampleMultiPolygonGeoJSON fill=fill}}
    {{/leaflet-map}}
  `);
  this.set('fill', '#ff0000');
// $('path').polygonPath[0].attributes.fill.value !== '#ff0000'
```

Not sure if this is the correct way to create a new test, but I want to make sure I'm not missing anything. Documentation seems to suggest style changes are updated from bound properties. 

Happy to continue looking into why this is but want to sanity check what I'm seeing first. Thanks.

Seems somewhat related to activity in #123.

### CODE REVIEW

**Comment by miguelcobain** [comment]
This is related to https://github.com/miguelcobain/ember-leaflet/pull/123

The way to solve this is to include the style mixin in the geojson layer.
Can you see if doing that fixes your test?

**Comment by allthesignals** [comment]
@miguelcobain sure, thank you, I'll try that, but I thought it was already included here? https://github.com/allthesignals/ember-leaflet/blob/master/addon/components/geojson-layer.js#L2

**Comment by miguelcobain** [comment]
@allthesignals correct. something fishy is happening.

**Comment by allthesignals** [comment]
Alright, I'll keep digging. Thank you! Maybe @knownasilya has some thoughts, considering he's working on a related issue.

**Comment by miguelcobain** [comment]
This should be fixed on master. Please reopen if that is not the case. Thank you.

**Pull request closed without merging**
