### PR TITLE
Using #-in-element instead of ember-wormhole

### PR DESCRIPTION
**Pull request by kaermorchen**
#-in-element has less size and more performance

### CODE REVIEW

**Comment by kaermorchen** [comment]
Is it my fail or some problems with tests?

**Comment by miguelcobain** [comment]
This was already released back in `0.0.10`. Thanks.

**Comment by miguelcobain** [comment]
My bad. Got confused with ember-composability-tools repo.

Can you change `{{#-in-element` to `{{#in-element`?

**Comment by miguelcobain** [comment]
I just did it myself.
Thanks! With this and the ember-composability-tools bump, ember-leaflet is completely free from ember-wormhole. 👍

**Pull request merged**
