### PR TITLE
Basic failing test for changing styles on event

### PR DESCRIPTION
**Pull request by knownasilya**
I'm not sure if I'm doing the events correct here

### CODE REVIEW

**Comment by knownasilya** [comment]
The only workaround that works for me is to create a new geojson layer based on the state with the colors set statically.

**Comment by miguelcobain** [comment]
Does this only happen for mouse events or it also fails with a basic `set` to a different property?

**Comment by knownasilya** [comment]
It seems to work with a basic set.

**Comment by miguelcobain** [comment]
So, I've added this test (an updated version of it) and indeed it was failing.
Then I fixed geojson layer to actually recreate the layers with the correct options.

Commit was https://github.com/miguelcobain/ember-leaflet/commit/1196d02390d3cd3e5bc8b0c61812f6659c488845

Thank you!

**Pull request closed without merging**
