### PR TITLE
Fixes TypeError: Cannot read property addEventListener of undefined

### PR DESCRIPTION
**Pull request by plcarmel**
I don't know why I am the only one that seems to experience this problem but this fix is really helping me.

I display a popup window automatically upon loading of the webpage. Without this fix, it doesn't show up the first time I try to do so.

Thank you

### CODE REVIEW

**Comment by miguelcobain** [comment]
> I display a popup window automatically upon loading of the webpage. Without this fix, it doesn't show up the first time I try to do so.

How are you doing this? I'd like to track down what's happening.

**Comment by plcarmel** [comment]
@miguelcobain, I do it by using the `popupOpen` attribute.

```htmlbars
        {{#leaflet-map
          lat=map.lat
          lng=map.lng
          zoom=map.zoom
          maxZoom=16
          scrollWheelZoom=false
          onMoveend=(action 'onMoveEnd')
          onZoomend=(action 'onZoomEnd')
          as |layers|
        }}
          {{layers.tile url="..."}}
          {{#marker-cluster-layer as |cluster|}}
            {{#each map.markers as |marker|}}
              {{#cluster.marker
                icon=icon
                lat=marker.lat
                lng=marker.lng
                onClick=(action 'onMarker' marker)
                as |map-marker|
              }}
                {{#map-marker.popup popupOpen=(eq marker currentMarker)}}
                  {{!...}}
                {{/map-marker.popup}}
              {{/cluster.marker}}
            {{/each}}
          {{/marker-cluster-layer}}
        {{/leaflet-map}}
```

**Comment by miguelcobain** [comment]
Could it be related with marker-cluster-layer?
I think we have tests that prove this works. It would be great to have a failing test.

**Comment by plcarmel** [comment]
Ok, I will work on this.

**Comment by plcarmel** [comment]
@miguelcobain, I have done my homework.

`popup-layer` is making the assumption that a marker is always added to the map.  `leaflet.marker-cluster` is breaking this assumption by storing markers without adding them to the map when they are clustered.

So this needed to be fixed. I added an integration test that basically just uses `leaflet.marker cluster` , adds a couple of markers and check that there are not exceptions. I am not sure if you are ok with it or if you would like something simpler...

I also added a feature that I need in my app if I want my map to behave the way I want it to. I added a flag (`alwaysBound`), true by default, that controls whether the popup is bound to to the marker the entire time or only when it becomes visible (through the `popupVisible` attribute). This way, a click on a marker does not automatically opens the popup; it becomes the responsibility of the developer to implement this logic.

I am waiting for your take on this.

**Comment by plcarmel** [comment]
On a side note, I should tell you that I greatly appreciate your work and that I would be unable to do the mine without passionate people like you. If you need help on specific parts of your opensource projects, I will be happy to do what I can to assist you. :)

**Comment by plcarmel** [comment]
@miguelcobain, do you have time to check this PR ?

**Comment by plcarmel** [comment]
@miguelcobain, just an other ping

**Comment by plcarmel** [comment]
@miguelcobain, if you don't have time, can you ask for someone else to have a look at it.  Anything more that I can do ?

**Comment by david-duncan** [comment]
Just wanted to drop a comment - We've had this forked internally for over a year now with a fix similar to above.

There is indeed a conflict between ember-leaflet and ember-leaflet-marker-cluster.

If this is fixed, this can resolve several open issues on the tracker currently. Until then, we will continue to update our fork.

**Comment by plcarmel** [comment]
Hi @miguelcobain ,

Would you be kind enough to review and merge this PR ? I have updated it by removing the unrelated new feature (I will create an other pull request for that) and by moving the inclusion of leaflet-marker-cluster from index.js to ember-cli-build.js. That way, it doesn't impact the addon while still providing the ability to test compatibility of the popup layer with leaflet-marker-cluster.

This will likely benefit many people.

**Comment by miguelcobain** [comment]
@plcarmel @david-duncan can you please try master?
I also applied the same fix to tooltip layers, in case some plugin does the same kind of trickery as marker cluster does.

I didn't merge this PR because I used ember-leaflet-marker-cluster instead of Leaflet.markercluster directly. Also my updates brought some conflicts.

I took this test. 👍 

I owe you guys a big apology. This has been far too long.

**Comment by plcarmel** [comment]
No worries. Works great ! thanks @miguelcobain.

**Pull request closed without merging**
