### PR TITLE
layers#geojson Change styles on `style` update

### PR DESCRIPTION
**Pull request by knownasilya**
Basically if `{{layers.geojson style=myStyle}}` changes, it will update the styles on the geojson.

### CODE REVIEW

**Comment by miguelcobain** [comment]
@knownasilya geojson-layer includes the Style mixin, which should solve this use case, right?

**Comment by knownasilya** [comment]
It doesn't work 😏

**Comment by miguelcobain** [comment]
So, you can't use individual style properties? What is the use case?

**Comment by knownasilya** [comment]
Use case is being able to use the `style` attribute correctly 👍  basically if you have advanced style
logic, then putting them in the template is super dirty, especially if you need to compute something.

**Comment by knownasilya** [comment]
@miguelcobain thoughts on this?

**Comment by miguelcobain** [comment]
@knownasilya just to make sure I got your PR. It is something that could be solved if we had a splat operator, right?
i.e
```hbs
{{marker-layer ...myStyleHash
```

instead of
```hbs
{{marker-layer opacity=myStyleHash.opacity stroke=myStyleHash.stroke
```

**Comment by knownasilya** [comment]
Exactly

**Comment by miguelcobain** [comment]
I don't mind the idea, but I think this belongs to the Style mixin. And would be great to have some tests.

**Comment by jayvarner** [comment]
Is this also a dup/different approach to #182? And is related to #136. Is there anything I can do to help add this functionality?

**Comment by knownasilya** [comment]
@jayvarner feel free to submit a PR against my fork or open a new one. I don't currently have the time to address @miguelcobain's last comment.

**Comment by jayvarner** [comment]
OK @knownasilya, I forked your fork and will give it a go. Thanks for getting it started.

**Comment by jayvarner** [comment]
As pointed out by @alkamin in #180, updating the style options works as expected if you skip clearing and re-adding the data on `didUpdateAttrs`. It appears that Leaflet's [`addData()`](https://github.com/Leaflet/Leaflet/blob/master/src/layer/GeoJSON.js#L120-L121) applies the options given to the layer when it was created.

I'm tinkering with ways to update the layer's options before calling `addData()`, but so far, everything I've tried is pretty ugly. Anyone got any brilliant ideas on a Friday afternoon?

**Comment by knownasilya** [comment]
It might be creating a new style object is the recommended way to go, because that would trigger a `didReceiveAttrs` or equivalent hooks.

**Comment by miguelcobain** [comment]
Adding `style` as a `leafletProperties` did the trick. Also added a test for it.
Please reopen if issue still persists.

**Pull request closed without merging**
